### ISSUE TITLE
VsBridge not listed in Stores -> Configuration

### ISSUE THREAD

**Issue by zadigus** [DivanteLtd/magento2-vsbridge#2]
Hi,
I followed the installation guide and tried to follow the instructions on "On-demand indexer (experimental!) support for mage2vuestorefront". 

After my call to 

```
php bin/magento setup:upgrade
```

I apparently lost my magento installation, i.e. browsing http://local.magento lead me to a page containing the following output:

```
Fatal error: Uncaught RuntimeException: Can't create directory /var/www/html/generated/code/Magento/Framework/App/ResourceConnection/. in [Magento\Framework\App\ResourceConnection\Proxy] in /var/www/html/vendor/magento/framework/Code/Generator.php:115 Stack trace: #0 /var/www/html/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...') #1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...') #2 [internal function]: spl_autoload_call('Magento\\Framewo...') #3 /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...') #4 /var/www/html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...') #5 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Fra in /var/www/html/vendor/magento/framework/Code/Generator.php on line 115
```

I am working with the following magento2 docker image:

https://github.com/alexcheng1982/docker-magento2

It seems like I am using Magento 2.2.5. Is maybe magento2-vsbridge not compatible with that version of Magento?

**Comment by zadigus** [comment]
The problem doesn't seem to come from magento2-vsbridge. Indeed, I tried to 

1. reinstall magento2
2. run `php bin/magento2 setup:upgrade`

and I got the same error as in my previous comment, without adding the `Divante` folder to the `app` folder.

**Comment by zadigus** [comment]
Soooo. I browsed the web a bit and was finally able to start magento after addition of the `Divante` folder and the call to `php bin/magento2 setup:upgrade`. I set full permission to the `/var/www/html/generated` folder. 

When I browse Stores -> Configuration in Magento's admin panel, however, I don't see anything related to the vsbridge.

**Comment by enricodeleo** [comment]
Same issue here. Where can I find this setting page?
